# Generated by Django 4.2.7 on 2025-01-12 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_create_default_roles"),
        ("authentication", "0002_role_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = []
