# Generated by Django 4.2.7 on 2025-01-10 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={
                "ordering": ["-upload_started_at"],
                "verbose_name": "file",
                "verbose_name_plural": "files",
            },
        ),
        migrations.AlterModelOptions(
            name="filechunk",
            options={
                "ordering": ["chunk_number"],
                "verbose_name": "file chunk",
                "verbose_name_plural": "file chunks",
            },
        ),
        migrations.AlterModelOptions(
            name="fileversion",
            options={
                "ordering": ["-version_number"],
                "verbose_name": "file version",
                "verbose_name_plural": "file versions",
            },
        ),
        migrations.RenameField(
            model_name="file",
            old_name="encryption_iv",
            new_name="iv",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="created_at",
            new_name="upload_started_at",
        ),
        migrations.RenameField(
            model_name="fileversion",
            old_name="encryption_iv",
            new_name="iv",
        ),
        migrations.RemoveField(
            model_name="file",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="filechunk",
            name="encrypted_path",
        ),
        migrations.RemoveField(
            model_name="filechunk",
            name="encryption_iv",
        ),
        migrations.RemoveField(
            model_name="filechunk",
            name="encryption_key",
        ),
        migrations.RemoveField(
            model_name="filechunk",
            name="is_uploaded",
        ),
        migrations.AddField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="file",
            name="last_accessed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="file",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("UPLOADING", "Uploading"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="tags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="file",
            name="upload_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filechunk",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("UPLOADING", "Uploading"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="filechunk",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="file",
            name="encrypted_path",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="encryption_key",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="file",
            name="mime_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="filechunk",
            name="chunk_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="filechunk",
            name="size",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="file_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="encrypted_path",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="encryption_key",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["owner", "status"], name="files_file_owner_i_1c981d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["upload_started_at"], name="files_file_upload__a050d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["name"], name="files_file_name_350fdc_idx"),
        ),
        migrations.AlterModelTable(
            name="file",
            table=None,
        ),
        migrations.AlterModelTable(
            name="filechunk",
            table=None,
        ),
        migrations.AlterModelTable(
            name="fileversion",
            table=None,
        ),
    ]
